#!/bin/bash
#
# Liver disease exploratory data analysis.
#

# Create virtual environment.
uv venv --prompt ldc --clear

# Activate virtual environment.
source .venv/bin/activate

# Install dependencies.
uv pip install -e . ".[dev]"

# Enable command-line autocompletion for the `liver` command.
eval "$(register-python-argcomplete liver)"
